/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Banco.ConexaoBanco;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alysson
 */
public class PesquisaAlunos extends javax.swing.JFrame {
 private Connection connection= null;
    private  Statement stm=null;
    public ResultSet rs=null;
    
  public  void  conecta(){
   
  }
 
  	
   
   
    /**
     * Creates new form PesquisaAlunos
     */
    public PesquisaAlunos() {
        initComponents();
      
   
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesquisa = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPesquisa.setColumns(20);
        txtPesquisa.setRows(5);
        jScrollPane1.setViewportView(txtPesquisa);

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Deletar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int valor;
String ID;
    String driver="com.mysql.jdbc.Driver";
    String servidor="jdbc:mysql://localhost:3306/escolaOnline";
    String usuario="root";
    String senha="";
    
    try{
    Class.forName(driver);
    this.connection=DriverManager.getConnection(servidor,usuario,senha);
    this.stm=this.connection.createStatement();
    
    }catch(Exception e){
    System.out.println("Erro "+e);
    }
    valor=Integer.parseInt(JOptionPane.showInputDialog("Digite 1 para Pesquisar Tudo\n 2 Para Pesquisar Por ID"));
    if(valor==1){
 try{
		String tabela="SELECT * FROM aluno";	
		this.rs=stm.executeQuery(tabela);	
		this.stm=this.connection.createStatement();
		
                while(this.rs.next()){
                    String id=rs.getString("id");
                    String nome=rs.getString("nome");
                    String turno=rs.getString("turma");
                   txtPesquisa.append("ID: "+id+"| Nome: "+nome+"| Turno: "+turno+"\n");
                
               
		}
		}catch(Exception e){
			System.out.println("erro na coluna");
			
		}	
    }
      if(valor==2){
          ID=JOptionPane.showInputDialog("Qual o ID");
 try{
		String tabela="SELECT * FROM aluno WHERE id IN('"+ID+"')";	
		this.rs=stm.executeQuery(tabela);	
		this.stm=this.connection.createStatement();
		
                while(this.rs.next()){
                    String id=rs.getString("id");
                    String nome=rs.getString("nome");
                    String turno=rs.getString("turma");
                   txtPesquisa.append("ID: "+id+"| Nome: "+nome+"| Turno: "+turno+"\n");
                
               
		}
		}catch(Exception e){
			System.out.println("erro na coluna");
			
		}	
    }




// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String nome,idade,id,turma,cpf;
        
  String driver="com.mysql.jdbc.Driver";
    String servidor="jdbc:mysql://localhost:3306/escolaOnline";
    String usuario="root";
    String senha="";
    
    try{
    Class.forName(driver);
    this.connection=DriverManager.getConnection(servidor,usuario,senha);
    this.stm=this.connection.createStatement();
    
    }catch(Exception e){
    System.out.println("Erro "+e);
    }
    id=JOptionPane.showInputDialog("Informe o ID");
    nome=JOptionPane.showInputDialog("Informe o nome");
    idade=JOptionPane.showInputDialog("Informe a idade");
    turma=JOptionPane.showInputDialog("Informe a turma");
    cpf=JOptionPane.showInputDialog("Informe o CPF");


try{
		String tabela="UPDATE aluno SET nome='"+nome+"', idade='"+idade+"', turma='"+turma+"', cpf='"+cpf+"'WHERE id="+id+";";	
		this.stm.executeUpdate(tabela);	
			
		}catch(Exception e){
			System.out.println("erro na edição: "+e.getMessage());
			
		}	


txtPesquisa.append("");




// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       String ID;
    String driver="com.mysql.jdbc.Driver";
    String servidor="jdbc:mysql://localhost:3306/escolaOnline";
    String usuario="root";
    String senha="";
    
    try{
    Class.forName(driver);
    this.connection=DriverManager.getConnection(servidor,usuario,senha);
    this.stm=this.connection.createStatement();
    
    }catch(Exception e){
    System.out.println("Erro "+e);
    }   
    ID=JOptionPane.showInputDialog("Informe o ID");
try{
		String tabela="DELETE FROM aluno WHERE id='"+ID+"';";	
		this.stm.executeUpdate(tabela);	
			
		}catch(Exception e){
			System.out.println("erro na edição: "+e.getMessage());
			
		}	     



txtPesquisa.append("");









// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
